jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    timeoutInMinutes: 360
    steps:
      - script: echo teste  # Template reference

  - job: macOS
    pool:
      vmImage: 'macOS-10.14'
    timeoutInMinutes: 360
    steps:
      - script: echo teste  # Template reference

  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    timeoutInMinutes: 360
    steps:
      - script: echo teste  # Template reference